name: Scrape and Update MongoDB

on:
  schedule:
    - cron: '0 * * * *'   # Every hour
  workflow_dispatch:       # Allow manual run

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python scraper.py
